# Generated by Django 5.2.7 on 2026-01-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
        ('provider_app', '0002_remove_service_description_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.providerservice'),
        ),
    ]
