# Generated by Django 5.2.7 on 2026-01-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_alter_booking_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='provider_service',
        ),
    ]
