# Generated by Django 5.2.7 on 2026-01-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
